# -*- coding: utf-8 -*-
"""FAQ Zensea : 7 rubriques, 48 réponses."""
P = lambda *x: "".join("<p>%s</p>" % s for s in x)

FAQ = {
'faq_choisir': ("Bien choisir son instrument", "Les questions qu'on se pose devant l'écran, avant de cliquer.", [
 ("Il faut savoir jouer d'un instrument pour commencer ?",
  P("Non, et ce n'est pas une formule commerciale. Sur un handpan comme sur un tongue drum, <strong>toutes les notes appartiennent à une seule et même gamme</strong> : elles s'accordent entre elles quel que soit l'ordre dans lequel vous les jouez. La fausse note n'existe pas.",
    "C'est ce qui rend l'instrument unique : vous ne travaillez pas, vous cherchez. Et vous tombez toujours sur quelque chose de beau. La majorité de nos clients n'avaient jamais touché un instrument, et jouent quelque chose d'agréable dès le premier soir.")),
 ("9, 10 ou 12 notes : lequel prendre ?",
  P("<strong>9 notes</strong> pour débuter : le format le plus lisible, on repère les notes du regard et on improvise sans réfléchir. C'est le choix que personne n'a jamais regretté.",
    "<strong>10 notes</strong> ajoutent une couleur harmonique sans compliquer la lecture. Le bon compromis si vous hésitez.",
    "<strong>12 notes</strong> offrent la palette la plus large et permettent de vrais morceaux avec des accords. Demande quelques mois de pratique pour être exploité.",
    "Dans le doute, prenez neuf. On progresse toujours vers plus de notes, jamais l'inverse.")),
 ("Qu'est-ce qu'une gamme, et laquelle choisir ?",
  P("La gamme est l'ensemble des notes gravées sur l'instrument. Elle décide de la <strong>couleur émotionnelle</strong> de tout ce que vous jouerez — bien plus que le nombre de notes.",
    "Les gammes <strong>mineures</strong> (D Kurd, Celtic minor, Amara) sonnent profondes, contemplatives, un peu mélancoliques. Elles représentent l'immense majorité des handpans joués, et c'est le son qu'on a en tête quand on pense « handpan ».",
    "Les gammes <strong>majeures</strong> sont plus lumineuses, plus joyeuses, et beaucoup plus rares.",
    "Si vous ne savez pas, prenez une gamme mineure : c'est ce que vous avez entendu et ce qui vous a donné envie.")),
 ("Handpan ou tongue drum : quelle différence ?",
  P("Le <strong>handpan</strong> est une coupole d'acier martelé qu'on joue aux mains. La résonance est ample, longue, elle remplit la pièce. C'est l'instrument le plus expressif des deux, et le plus cher.",
    "Le <strong>tongue drum</strong> est une sphère ou un disque d'acier découpé en lames, qu'on joue aux mailloches ou du bout des doigts. Le son est plus doux, plus court, plus contenu. Il coûte cinq à dix fois moins cher.",
    "Beaucoup commencent par le tongue drum et gardent les deux. Aucun des deux ne remplace l'autre.")),
 ("Quel budget prévoir vraiment ?",
  P("Un tongue drum d'entrée de gamme se trouve autour de <strong>25 €</strong>, un modèle de salon à onze notes autour de <strong>70 €</strong>. Une kalimba tourne autour de <strong>30 à 60 €</strong>, un bol chantant entre <strong>50 et 150 €</strong> selon le format.",
    "Un handpan sérieux commence autour de <strong>400 €</strong>. En dessous de 250 €, méfiez-vous : ce sont presque toujours des instruments mal accordés dont les notes bavent les unes sur les autres dès qu'on enchaîne.",
    "Le pack complet — housse, mailloches, huile, livret — est inclus chez nous. Ailleurs, il faut souvent compter 60 à 100 € de plus.")),
 ("Est-ce un bon cadeau pour quelqu'un qui n'est pas musicien ?",
  P("C'est probablement le meilleur cas d'usage. Un handpan ou un tongue drum ne demande aucune compétence préalable, sonne juste dès la première minute, et ne provoque jamais la frustration d'un instrument qu'on n'arrive pas à faire sonner.",
    "Pour un cadeau, prenez un <strong>9 notes en gamme mineure</strong> ou un <strong>tongue drum 11 notes</strong> : les deux formats les plus immédiats. Et si le son ne parle pas à la personne, elle a 30 jours pour changer d'avis.")),
 ("Est-ce que les enfants peuvent en jouer ?",
  P("Oui, et c'est souvent eux qui s'en emparent le plus vite. Le tongue drum est particulièrement adapté : léger, sans arête vive, impossible à désaccorder en jouant, et immédiatement gratifiant.",
    "Pour un enfant de moins de huit ans, préférez un <strong>tongue drum 15 cm</strong> ou une <strong>kalimba</strong>. Un handpan de 22 pouces reste lourd et encombrant pour de petites mains.")),
 ("Puis-je jouer en appartement sans gêner les voisins ?",
  P("Un tongue drum, une kalimba et un ocarina se jouent sans problème le soir : le volume reste proche de celui d'une conversation.",
    "Un handpan porte davantage — comptez le volume d'une guitare acoustique jouée doucement. En appartement, jouez-le sur les genoux plutôt que sur un support (le corps absorbe une partie des vibrations) et évitez de le poser directement sur une table, qui fait caisse de résonance.")),
]),
'faq_installation': ("Prise en main & premiers pas", "Vous n'êtes pas musicien. Ce n'est pas un problème.", [
 ("Comment tenir un handpan correctement ?",
  P("Sur les genoux, le creux tourné vers vous, légèrement incliné. Les avant-bras restent détendus et les épaules basses : <strong>la position fait la moitié du son</strong>. Un instrument tenu de façon crispée sonne mat.",
    "Évitez de le poser à plat sur une table : le contact étouffe la résonance. Si vous voulez jouer debout ou longtemps, un support dédié laisse l'instrument vibrer librement.")),
 ("Avec quoi frappe-t-on : les doigts, la paume, les mailloches ?",
  P("Sur un handpan : <strong>le bout des doigts, jamais la paume et jamais la force</strong>. Un rebond sec au centre de la note, et l'acier chante tout seul pendant plusieurs secondes. Frapper fort ne donne pas plus de son, seulement un son plus dur — et à la longue, cela désaccorde l'instrument.",
    "Sur un tongue drum : mailloches ou doigts, au choix. Les mailloches donnent une attaque nette, les doigts un son plus rond. La plupart des joueurs alternent selon le morceau.")),
 ("Combien de temps avant de jouer quelque chose d'écoutable ?",
  P("Une soirée. Ce n'est pas une exagération : comme toutes les notes s'accordent entre elles, votre premier enchaînement au hasard sonne déjà juste.",
    "Ce que vous travaillerez ensuite, ce n'est pas la justesse mais le <strong>rythme</strong> et les <strong>nuances</strong> — jouer plus doux, laisser respirer, ne pas remplir tous les silences. C'est là que se joue la différence entre quelqu'un qui débute et quelqu'un qui joue depuis un an.")),
 ("Faut-il prendre des cours ?",
  P("Non, et c'est rare de pouvoir le dire d'un instrument. La majorité des joueurs de handpan sont autodidactes.",
    "Le livret de partitions numérotées fourni suffit pour vos premiers morceaux. Ensuite, quelques vidéos suffisent à comprendre les techniques de base — le roulement des doigts, l'attaque sur le bord de la note, l'usage des harmoniques.",
    "Un cours devient utile après six mois ou un an, quand on cherche à structurer ce qu'on improvise.")),
 ("Comment lire le livret de partitions ?",
  P("Les notes sont <strong>numérotées</strong> sur l'instrument et le livret indique simplement quel numéro jouer, dans quel ordre. Vous lisez des chiffres, pas du solfège.",
    "C'est le même principe sur la kalimba, dont les lames sont numérotées, et sur l'ocarina, dont le livret montre chaque doigté en image, trou par trou.")),
 ("Puis-je jouer avec d'autres instruments ?",
  P("Oui, à condition que la gamme soit compatible. Tous nos instruments sont accordés au <strong>diapason 440 Hz</strong> — l'accordage standard international — donc ils sont justes par rapport à un piano, une guitare ou un violon.",
    "Reste la question de la gamme : un handpan en D Kurd s'accorde naturellement avec tout ce qui est en ré mineur. Indiquez-nous ce avec quoi vous voulez jouer, on vous oriente vers la bonne gamme.")),
 ("Mon instrument sonne mat, qu'est-ce que je fais mal ?",
  P("Trois causes, dans l'ordre de fréquence. <strong>Vous frappez trop fort</strong> : l'acier n'a pas le temps de vibrer. <strong>Vous frappez avec la paume</strong> ou avec la pulpe entière du doigt au lieu du bout. <strong>L'instrument est posé sur une surface qui l'étouffe</strong> — une table, un coussin trop mou, vos cuisses trop serrées.",
    "Essayez : posez-le sur les genoux légèrement écartés, et frappez du bout de l'index avec un rebond immédiat. La différence est spectaculaire.")),
 ("Quel accessoire est vraiment utile au début ?",
  P("La <strong>housse</strong>, et elle est déjà dans le carton. C'est le seul accessoire indispensable : la quasi-totalité des instruments désaccordés le sont à cause d'un choc pendant un transport.",
    "Le <strong>support</strong> devient utile si vous jouez souvent plus d'une heure ou si vous jouez debout. Les <strong>mailloches de rechange</strong> et l'<strong>huile d'entretien</strong> peuvent attendre quelques mois.")),
]),
'faq_lumiere': ("Accordage, gammes & entretien", "Ce qui fait qu'un instrument reste juste dix ans.", [
 ("Qu'est-ce que le 440 Hz, et pourquoi c'est important ?",
  P("440 Hz est la fréquence du la de référence, le <strong>standard international</strong> utilisé par tous les orchestres et tous les instruments du commerce.",
    "Un instrument accordé en 440 Hz est jouable avec n'importe quel autre instrument. Un instrument accordé en 432 Hz — qu'on trouve parfois dans le milieu du bien-être — sonne très bien seul, mais devient faux dès que vous jouez avec quelqu'un.",
    "Tous nos instruments sont en 440 Hz, et c'est écrit sur chaque fiche.")),
 ("Est-ce que ça se désaccorde avec le temps ?",
  P("Un handpan bien traité garde son accord <strong>des années</strong>. Ce qui désaccorde un instrument, ce n'est jamais l'usage normal : c'est un choc, une chaleur excessive ou la corrosion.",
    "Trois règles suffisent : ne jamais le laisser en plein soleil ou dans une voiture l'été, ne jamais frapper avec la paume ou avec un objet dur, et le ranger dans sa housse dès qu'il ne sert pas.")),
 ("Comment entretenir l'acier ?",
  P("Un passage de chiffon microfibre après chaque séance pour retirer la transpiration — c'est elle qui attaque l'acier, pas l'air.",
    "Une fois par mois, quelques gouttes de l'<strong>huile fournie</strong> réparties au chiffon sur toute la surface. Cela crée un film protecteur invisible contre la corrosion.",
    "Si des points de rouille apparaissent malgré tout, un chiffon légèrement abrasif et de l'huile suffisent à les faire disparaître avant qu'ils ne s'installent.")),
 ("Peut-on faire réaccorder un handpan ?",
  P("Oui. C'est un travail d'accordeur spécialisé, qui remartèle les zones concernées au marteau et à l'oreille. Comptez généralement 100 à 200 € et quelques semaines de délai.",
    "En pratique, la question ne se pose qu'après un choc ou après plusieurs années d'usage intensif. Écrivez-nous : on vous orientera vers un accordeur près de chez vous.")),
 ("En quel acier sont faits vos handpans ?",
  P("En acier <strong>nitruré</strong>, traité thermiquement pour durcir la surface et résister à la corrosion. C'est le traitement qui donne la teinte sombre caractéristique et qui permet à l'instrument de tenir son accord dans le temps.",
    "Un handpan en acier brut non traité coûte moins cher à produire mais rouille en quelques mois si vous ne l'huilez pas religieusement.")),
 ("Comment le transporter en avion ou en train ?",
  P("En train, aucun problème : la housse suffit. En avion, un handpan dans sa housse rembourrée passe généralement en <strong>bagage cabine</strong> sur les compagnies régulières, mais la règle varie — vérifiez les dimensions autorisées avant de réserver.",
    "Ne le mettez jamais en soute sans caisse rigide : c'est le meilleur moyen de le récupérer désaccordé.")),
 ("La kalimba a besoin d'être accordée ?",
  P("Oui, de temps en temps, et c'est très simple. Un <strong>marteau d'accordage</strong> est fourni : on tape légèrement sur la lame pour la faire coulisser. La lame s'allonge, la note descend ; elle raccourcit, la note monte.",
    "Une application gratuite d'accordeur sur téléphone suffit à contrôler. Comptez cinq minutes pour l'instrument entier, deux à trois fois par an.")),
 ("Le bol chantant demande-t-il un entretien ?",
  P("Très peu. Un chiffon sec après usage suffit : le laiton se patine avec le temps, et cette patine fait partie de l'objet — la faire disparaître au produit abrasif abîme le son.",
    "Gardez simplement le coussin propre et sec : c'est lui qui isole le bol de la table et qui laisse la résonance se développer.")),
]),
'faq_livraison': ("Livraison & suivi", "Un instrument accordé voyage bien, à condition d'être bien calé.", [
 ("Quels sont vos délais de livraison ?",
  P("Préparation en <strong>24 à 48 h ouvrées</strong> après votre commande, puis <strong>7 à 13 jours ouvrés</strong> de transport. Soit <strong>8 à 15 jours ouvrés au total</strong>.",
    "Vous recevez un numéro de suivi par e-mail dès le départ du colis.")),
 ("La livraison est-elle gratuite ?",
  P("La livraison est <strong>offerte dès 30 € d'achat</strong>. En dessous, les frais s'affichent au panier, avant validation — jamais à la dernière étape.")),
 ("Comment mes instruments sont-ils emballés ?",
  P("C'est le premier reproche fait aux vendeurs d'instruments en ligne, et le point sur lequel nous ne transigeons pas : <strong>housse déjà en place autour de l'instrument</strong>, puis calage mousse, puis double carton.",
    "Un handpan qui bouge dans son colis est un handpan qui arrive désaccordé. Le nôtre ne bouge pas.")),
 ("Puis-je suivre ma commande et changer l'adresse ?",
  P("Le suivi est disponible dès l'expédition, via le lien reçu par e-mail.",
    "Pour un changement d'adresse, écrivez-nous <strong>le plus vite possible</strong> à contact.zensea@gmail.com : tant que le colis n'est pas parti, c'est traité dans la journée.")),
 ("Livrez-vous hors de France ?",
  P("Nous livrons en <strong>France métropolitaine</strong>, ainsi qu'en Belgique, au Luxembourg et en Suisse. Les délais et frais éventuels apparaissent au moment du paiement, avant validation.",
    "Pour la Corse et les DOM-TOM, écrivez-nous avant de commander : les délais sont plus longs et nous préférons vous les annoncer honnêtement.")),
 ("Que se passe-t-il si je ne suis pas là à la livraison ?",
  P("Le transporteur laisse un avis de passage et propose une nouvelle date ou un point relais.",
    "Un conseil : ne faites pas livrer un handpan en point relais si vous pouvez l'éviter. Un colis manipulé une fois de plus est un risque de plus.")),
]),
'faq_retours': ("Retours & remboursement", "Nos engagements, écrits noir sur blanc — et vos droits.", [
 ("Mon instrument est arrivé abîmé. Que faire ?",
  P("Vous êtes couvert, entièrement. En vente à distance, <strong>le vendeur est responsable du colis jusqu'à sa réception</strong>.",
    "Prenez une photo du carton et de l'instrument, envoyez-la à contact.zensea@gmail.com dans les jours qui suivent, et nous remplaçons ou remboursons. Aucune expertise à vos frais, aucun formulaire à rallonge.")),
 ("Puis-je retourner un instrument si le son ne me plaît pas ?",
  P("Oui. Vous disposez de <strong>30 jours</strong> à compter de la réception pour changer d'avis, sans avoir à vous justifier — bien au-delà des 14 jours légaux.",
    "L'instrument doit revenir dans son emballage d'origine et en état de revente. <strong>Les frais de retour sont à votre charge.</strong>")),
 ("Comment se passe un remboursement ?",
  P("Sur le <strong>moyen de paiement utilisé à la commande</strong>, sous <strong>7 à 14 jours</strong> après réception et validation du retour.",
    "Vous recevez un e-mail de confirmation au moment où le remboursement part de chez nous.")),
 ("Et si l'instrument arrive désaccordé ?",
  P("C'est un défaut de conformité, pas un changement d'avis : dans ce cas <strong>nous prenons les frais de retour à notre charge</strong> et nous remplaçons l'instrument.",
    "Chaque instrument est joué note par note avant expédition, donc le cas est rare — mais il peut arriver après un transport violent, et c'est notre responsabilité.")),
 ("Puis-je annuler ou modifier ma commande ?",
  P("Oui, tant qu'elle n'est pas expédiée. Écrivez-nous immédiatement, c'est traité dans la journée.",
    "Après l'expédition, il faut passer par le retour classique sous 30 jours.")),
 ("Vendez-vous les accessoires séparément ?",
  P("Oui : housses, supports, mailloches de rechange, huile d'entretien et livrets sont disponibles à l'unité dans la rubrique Accessoires.",
    "Si vous cherchez une pièce précise qui n'y figure pas, écrivez-nous — on trouve généralement.")),
 ("Faites-vous des factures pour une structure ?",
  P("Oui. Écoles de musique, associations, praticiens : ouvrez un compte via l'Espace pro et vous recevrez une facture au nom de votre structure, avec des tarifs dégressifs et un paiement à 30 jours possible.")),
]),
'faq_securite': ("Qualité, contrôle & la marque", "Ce qui distingue un instrument d'un objet décoratif.", [
 ("Comment contrôlez-vous l'accordage ?",
  P("Chaque instrument est <strong>joué note par note</strong> avant expédition et contrôlé au diapason 440 Hz. Pas un scan automatique : une oreille humaine, un instrument à la fois.",
    "On vérifie trois choses : la justesse de chaque note, la longueur de la résonance, et l'absence de <strong>bavure</strong> — ce phénomène où deux notes voisines se déclenchent l'une l'autre, qui rend un instrument bon marché inutilisable dès qu'on enchaîne.")),
 ("Qu'est-ce qui fait qu'un handpan est mauvais ?",
  P("Trois défauts, toujours les mêmes. <strong>Les notes bavent</strong> les unes sur les autres. <strong>La résonance est courte</strong>, une seconde au lieu de cinq. <strong>La gamme n'est pas indiquée</strong>, parce que le fabricant lui-même ne la garantit pas.",
    "Ce sont exactement les trois points sur lesquels un instrument est refusé chez nous.")),
 ("Combien d'instruments refusez-vous ?",
  P("Beaucoup, et c'est le cœur du travail. Nous gardons peu de modèles, volontairement : un instrument qui ne passe pas le contrôle d'accordage ne part pas en ligne.",
    "C'est plus simple à dire qu'à faire — cela veut dire renvoyer des cartons entiers — mais c'est ce qui vous évite les mauvaises surprises.")),
 ("Qui êtes-vous vraiment ? Zensea est une entreprise française ?",
  P("Oui. Zensea est éditée par <strong>Abdellah El Moufid</strong>, 10 rue de Provence, 87220 Feytiat, France. Siren 994 612 109, Siret 99461210900011, APE 4791A.",
    "Le service client est français et répond du lundi au vendredi, de 9h à 18h, à contact.zensea@gmail.com ou au +33 7 56 88 21 12.")),
 ("Vos instruments sont-ils fabriqués en France ?",
  P("Non, et nous préférons le dire clairement plutôt que de laisser planer le doute. Nos instruments sont fabriqués par des ateliers spécialisés, puis <strong>contrôlés et réaccordés si nécessaire</strong> avant expédition.",
    "Ce que nous apportons, ce n'est pas la fabrication : c'est la sélection, le contrôle et le fait de vous répondre en français quand vous avez une question.")),
 ("Proposez-vous des instruments d'occasion ou reconditionnés ?",
  P("Pas pour l'instant. Un handpan d'occasion peut être excellent, mais son accord dépend entièrement de la façon dont il a été traité — et cela ne se voit pas sur une photo.",
    "Si vous en avez un à faire évaluer, écrivez-nous : on vous dira ce qu'il vaut, même si nous ne le rachetons pas.")),
]),
'faq_ventilateurs': ("Bols chantants & instruments d'éveil", "Ceux qu'on choisit pour l'ambiance plutôt que pour la mélodie.", [
 ("Comment fait-on chanter un bol ?",
  P("Posez le bol sur son coussin. <strong>Frappez une fois le bord</strong> avec le maillet pour lancer la note, puis faites tourner le maillet lentement contre la paroi extérieure, en gardant une <strong>pression constante</strong>.",
    "Le son monte au bout de deux ou trois tours. Le seul vrai point d'attention est la régularité du geste, pas la force.")),
 ("Quel format de bol choisir ?",
  P("<strong>12 à 15 cm</strong> : une note claire, montante, qui s'installe vite. C'est le bol qu'on garde à côté de soi pour marquer un début et une fin de séance.",
    "<strong>20 à 25 cm</strong> : le son descend, s'épaissit, et la résonance tient beaucoup plus longtemps. C'est celui qu'utilisent les praticiens, et celui qu'on entend dans toute la pièce.")),
 ("Martelé main ou usiné : ça change quelque chose ?",
  P("Oui, nettement. Un bol martelé à la main porte des <strong>micro-irrégularités</strong> qui enrichissent le spectre : le son est moins pur, plus vivant, avec des battements qui donnent cette impression de vibration flottante.",
    "Un bol usiné sonne plus « propre » et plus prévisible. C'est le martelé que nous sélectionnons.")),
 ("La kalimba, c'est pour les enfants ?",
  P("Pas seulement, même si c'est un excellent premier instrument. La kalimba est un vrai instrument mélodique : on y joue des morceaux complets, à deux pouces, avec des accompagnements.",
    "Sa force est ailleurs : elle tient dans une poche, elle se joue à volume très bas, et elle ne demande aucune installation. C'est l'instrument du train et du bureau.")),
 ("L'ocarina demande-t-il du souffle ?",
  P("Beaucoup moins qu'une flûte. Il n'y a <strong>ni embouchure à former, ni pression à maîtriser</strong> : vous soufflez doucement et régulièrement, et la note sort juste.",
    "La seule règle : ne pas forcer. Souffler trop fort fait monter la note d'un demi-ton et sonne faux. C'est le seul vrai apprentissage, et il tient en une phrase.")),
]),
}
